import matplotlib.pyplot as plt
import numpy as np
x=np.arange(1,6)
y=np.arange(2,11,2)
#fig=plt.figure()
#axes=fig.add_axes([0.1,0.2,0.3,0.4])
#plt.show()
# axes.plot(x,y)
# axes.set_xlabel('Inner x')
# axes.set_ylabel('Inner y')
# axes.set_title('Outter')
# plt.show()
#plt.plot(x,y,'green')
#plt.show()
# plt.subplot(2,2,1)
# plt.plot(x,y,'blue')
# plt.subplot(2,2,2)
# plt.plot(y,x,'red')
# plt.subplot(2,2,3)
# plt.plot(x**2,y**0.5,'purple')
# plt.subplot(2,2,4)
# plt.plot(y**2,x**0.5,'green')
# plt.show()
# fig,axes=plt.subplots(nrows=2,ncols=1,figsize=(5,5))
# #plt.tight_layout()
# axes[0]=plt.plot(x,y,'red')
# axes[0].set_title('1ST Graphic')
# axes[1]=plt.plot(y**3,x,'purple')
# axes[1].set_title('2ND Graphic')
# plt.show()
import pandas as pd
#x= np.arange(1,10)
#y=x**2
#plt.bar(x,y)
#plt.xlabel('x')
#plt.ylabel('y')
#plt.show()
liste=list(range(1,6))
df1=pd.DataFrame(liste)
df1.plot(grid=True,alpha=0.9,subplots=True)
plt.show()
